# backend/app/crud/user_crud.py
from pymongo.database import Database as MongoDatabase
from bson import ObjectId # Import ObjectId
from typing import Optional

from app.models.user_models import UserInDB, UserCreate
from app.core.config import settings
from app.core.security import get_password_hash # For creating user
from datetime import datetime

def get_user_by_email(db: MongoDatabase, email: str) -> Optional[UserInDB]:
    user_data = db[settings.USERS_COLLECTION].find_one({"email": email})
    if user_data:
        return UserInDB(**user_data)
    return None

def get_user_by_id(db: MongoDatabase, user_id: str) -> Optional[UserInDB]:
    try:
        user_oid = ObjectId(user_id)
    except Exception:
        return None # Invalid ObjectId format
    user_data = db[settings.USERS_COLLECTION].find_one({"_id": user_oid})
    if user_data:
        return UserInDB(**user_data)
    return None

def create_user(db: MongoDatabase, user: UserCreate) -> UserInDB:
    hashed_password = get_password_hash(user.password)
    
    # Ensure credits default if not provided, though Pydantic model should handle this
    credits = user.credits if user.credits is not None else settings.NEW_USER_CREDITS

    user_db_data = UserInDB(
        email=user.email,
        username=user.username,
        hashed_password=hashed_password,
        credits=credits,
        created_at=datetime.utcnow(),
        # id will be generated by MongoDB and handled by UserInDB model upon retrieval
    )
    
    # Use model_dump to get a dict suitable for MongoDB, excluding 'id' if it's None
    # and ensuring aliases are used (e.g., if _id is an alias for id in the model)
    user_dict_to_insert = user_db_data.model_dump(by_alias=True, exclude_none=True)
    
    # MongoDB will create the _id. We retrieve it to populate the returned UserInDB object.
    result = db[settings.USERS_COLLECTION].insert_one(user_dict_to_insert)
    
    # Fetch the inserted user to get the complete UserInDB object including the ID
    # This is safer than manually constructing it if there are defaults or transformations in the model
    created_user_data = db[settings.USERS_COLLECTION].find_one({"_id": result.inserted_id})
    if created_user_data:
        return UserInDB(**created_user_data)
    else:
        # This case should ideally not happen if insert_one was successful
        # Consider raising an error or handling appropriately
        raise Exception("Failed to retrieve user after creation")

